name: 'VPM package listing generator'
description: 'Generates or augments a VPM package listing with releases from a specified repository'
author: bd_
inputs:
  output:
    required: true
    description: Directory that will contain the resulting vpm files
  repository:
    required: false
    description: 'Repository to obtain releases from'
    default: ${{ github.repository }}
  package:
    required: true
    description: The VPM package name to include
  token:
    required: true
    description: The github auth token
  repo_url:
    required: true
    description: The published URL of this repository
  prerelease_repo_url:
    required: false
    description: The published URL of a repository to receive prereleases
    default:
  repo_author:
    required: true
    description: This repository's author
  repo_name:
    required: true
    description: The display name for the repository
  prerelease_repo_name:
    required: false
    description: The display name for the prerelease repository
    default:
  repo_id:
    required: false
    description: The id for the repository
  prerelease_repo_id:
    required: false
    description: The id for the prerelease repository
runs:
  using: 'node16'
  main: 'dist/index.js'
