# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Build/deploy
on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run test
          npm run package

      - name: Deploy to dist branch
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          git config user.email 'ci@fushizen.net'
          git config user.name 'Autobuild'
          git rm --cached -r dist || true
          git add -f dist
          git commit -m "Rebuild generated files"
          git push origin HEAD:refs/heads/dist --force

      - name: Deploy to dist branch
        if: ${{ github.ref == 'refs/heads/test' && github.event_name == 'push' }}
        run: |
          git config user.email 'ci@fushizen.net'
          git config user.name 'Autobuild'
          git rm --cached -r dist || true
          git add -f dist
          git commit -m "Rebuild generated files"
          git push origin HEAD:refs/heads/test-dist --force